apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kong-database
  name: kong-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-database
  strategy:
    type: Recreate
  template:
    metadata:
     labels:
        app: kong-database
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: kong
        - name: POSTGRES_USER
          value: kong
        image: postgres:9.5
        name: kong-database
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: kong-database-claim0
      restartPolicy: Always
      volumes:
      - name: kong-database-claim0
        persistentVolumeClaim:
          claimName: kong-database-claim0
    spec:
      containers:
      - env:
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8001
        - name: KONG_ADMIN_LISTEN_SSL
          value: 0.0.0.0:8444
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_LOG_LEVEL
          value: info
        - name: KONG_PG_HOST
          value: kong-database
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        image: kong:0.14.1
        name: kong
      restartPolicy: Always      

