apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kong-database
  name: kong-database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kong-database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: kong-database
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: kong
        - name: POSTGRES_USER
          value: kong
        image: postgres:9.5
        imagePullPolicy: ""
        name: kong-database
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: kong-database-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: kong-database-claim0
        persistentVolumeClaim:
          claimName: kong-database-claim0
status: {}
