apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kong
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - env:
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8001
        - name: KONG_ADMIN_LISTEN_SSL
          value: 0.0.0.0:8444
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_LOG_LEVEL
          value: info
        - name: KONG_PG_HOST
          value: kong-database
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        image: kong:0.14.1
        name: kong
        ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 8001
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8444
          protocol: TCP
      restartPolicy: Always
     
      