apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: "true"
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kong
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kong
  strategy: {}
  template:
    metadata:
      annotations:
        io.rancher.container.pull_image: always
        io.rancher.scheduler.global: "true"
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: kong
    spec:
      containers:
      - env:
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8001
        - name: KONG_ADMIN_LISTEN_SSL
          value: 0.0.0.0:8444
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_LOG_LEVEL
          value: info
        - name: KONG_PG_HOST
          value: kong-database
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        image: kong:0.14.1
        imagePullPolicy: ""
        name: kong
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
