apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    io.rancher.container.start_once: "true"
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kong-migration
  name: kong-migration
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kong-migration
  strategy: {}
  template:
    metadata:
      annotations:
        io.rancher.container.start_once: "true"
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: kong-migration
    spec:
      containers:
      - args:
        - sh
        - -c
        - kong migrations up && sleep 30
        env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_HOST
          value: kong-database
        image: kong:0.14.1
        imagePullPolicy: ""
        name: kong-migration
        resources: {}
        tty: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
