apiVersion: v1

kind: PersistentVolume
metadata:
  name: mongo-claim0
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  mountOptions:
    - hard
    - nfsvers=4.0
  nfs:
    server: 10.164.180.116
    path: /var/stgpool